name: 'elementalarsenal'
version: '${version}'
main: me.km127pl.elementalarsenal.ElementalArsenal
api-version: 1.19
authors: [ km127pl ]
description: an items plugin for block game
website: km127pl.us
